<?php $_helper = Mage::helper('tastehit_productrecommendation'); ?>
<?php if ($_helper->isEnabled()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var _thq = _thq || [];
        _thq.push(['setId', '<?php echo $_helper->getCustomerId(); ?>']);
        _thq.push(['trackPageView']);
        _thq.push(['trackEvents']);
        _thq.push(['detectChanges']);
        _thq.push(['displaySmartMenu']);

        (function() {
            var th=document.createElement('script');
            th.type='text/javascript';th.async=true;
            th.src=('https:'==document.location.protocol?
                    'https://':'http://') +
                'www.tastehit.com/static/th.js';
            var s=document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(th, s);
        })();
        //]]>
    </script>
<?php endif; ?>